### ISSUE TITLE
Visonic motion sensors

### ISSUE THREAD

**Issue by cjones813** [CrientClash/homeassistant#2]
Hello, Many thanks for this plugin. Can I add visonic motion sensors (PIRs) or is it just limited to contact sensors?

**Comment by a94marbo** [comment]
I dont think that the owner is doing anything with this component anymore. It have been dead for some time. The project was cloned here, and a few bugs was fixed.
https://github.com/And3rsL/VisonicAlarm-for-Hassio
I have used this new version successfully, but I have not got the sensors to work (or show up), only the alarm panel works for me.

**Comment by cjones813** [comment]
> 
> 
> I dont think that the owner is doing anything with this component anymore. It have been dead for some time. The project was cloned here, and a few bugs was fixed.
> https://github.com/And3rsL/VisonicAlarm-for-Hassio
> I have used this new version successfully, but I have not got the sensors to work (or show up), only the alarm panel works for me.

Many thanks for this info. Will give it a go tonight! Will update you to let you know if I can get motion sensors working. Thanks again!

**Comment by cjones813** [comment]
@a94marbo I have narrowed down the sensors not working due to them not 'pinging' the app with any status change.

I actually own a visonic server that runs powermanage this is what the 'Visonic-go' app connects to. In the server is a virtual keypad screen, once connected to the panel this shows what zone is violated etc wondering if there would be a way for this log to trigger a motion event. unfortunately I would not have the knowledge to put this in to action or code it!
<img width="776" alt="Screenshot 2019-12-03 at 17 31 44" src="https://user-images.githubusercontent.com/57048835/70074875-8ae94100-15f3-11ea-9e97-0857e2174e31.png">

**Comment by a94marbo** [comment]
Ahh, cool. Maybe we could move this conversation to the active project and hope that the owner can maybe apend a few hours to check this?

**Comment by cjones813** [comment]
@a94marbo just had I thought... on your visonic panel in the device settings, have you got "DISARM Activity" set to yes for each PIR sensor?

**Comment by a94marbo** [comment]
Hmmm, I cannot find that setting in the installation manual. What panel du you have? I have a powermaster 10.

**Comment by cjones813** [comment]
> Hmmm, I cannot find that setting in the installation manual. What panel du you have? I have a powermaster 10.

Yes should be there on PM10. Off the top of my head... installer mode > zones and devices > modify device > motion sensors > device settings > disarm activity > yes +0 seconds.

This will need to be done for each zone. After this is done when you return to the home screen and you should see ‘zone name - violated’ on the screen when motion is detected.

**Comment by cjones813** [comment]
@a94marbo 
![DE2A83D0-F06F-48D5-A4AE-AACDDF6C3E36](https://user-images.githubusercontent.com/57048835/70392744-28b98300-19db-11ea-8351-db108d7364a8.jpeg)
![56B4EB4A-38B7-45EA-BDD8-33976DFE8130](https://user-images.githubusercontent.com/57048835/70392745-28b98300-19db-11ea-8df0-20d74ab45cba.jpeg)
